name: CI for mobile test run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
        cache: 'npm'
    - name: Cache node modules
      id: node_modules_cache
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ${{github.workspace}}/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install node modules dependencies if missing
      if: steps.node_modules_cache.cache-hit != 'true'
      run: npm install

  test:
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.3'
    - name: Restore node cache
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ${{github.workspace}}/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - run: DEVICE_NAME='Pixel 5' npm run test

  upload-artifact:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results
        retention-days: 20

  allure-report:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
    - name: Get Allure history
      uses: actions/cache@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'Test report'
        state: 'success'
        sha: ${{ github.sha }}
        target_url: https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}


